apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustfs-pvc
  labels:
    app: rustfs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 35Gi
