---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-image-updater-git-creds
  namespace: argocd
spec:
  encryptedData:
    password: AgBQOwWQxUi60/PmbzbGRuFGQaMHavut6irA4f5e5Z07foCba5+n3MpI47FxhuN0blliYrPPJGWWyaXmI5J0U/3bFdzgusysB7WSkeLz1GPShf3NE/rUM6ciNCnU7xRcJfNqIjbWUVFPRVYXoqCsgVWThbDo3wtzRSkwXEwt+sseIWYwlQz25qS7/YkT88wDX0LX1PBSJoKBBhlqlRiUiR7lzrOIv6zoH/ZxpN/spEqIiHqocVSwJSW3quVnkTDBMkOznt17nCeeB4I54dUX81AsEKBR/DlxbXyKD08DAPjuHFvrSnkXjfAndsm77ovFrcn9t5P/YSTYi3r9epQltYs9uoZecrVyeIHtBkrZJ2eHvQAaiMsioBMdOzZiRFwxFB8pX9vUNC6cpD3F8x8R/nDmqOZfZpg5z0X1MLEGqtUKi+XSiqb549V2ne/oTQNr/3O4R0IRmgXBhLhVykZ+wsP5bC/nYZi1Otzs1dMzkn7d61cW5a1azV7WbXECHgmHXDMa6cbqkKxn3Y1xx2CgihYS7AYXuGstre57Xq3z1sF3QkRjtrHj4QBSMoqTszLFax/ateqq+3kGteNXr5RXeldaADcK7Uxn7jHGpKoTU5eyAk+KAFL5w+jRHWz8ZRIyIE12q8JgZiw7QtmyfoiD2NXlzsXtJN++4K/5tRnjAYcrm8JHeCivPMrsxAWZWj/XnEdbJIPp2i1AvGqC2XodizEsmli4VOVUnZQzvSK3LFDMeLa6qqh9aOWQ
    username: AgAy1yTkVWgn6VCQ8/HQByp3ORUuwn4viiVHoLdTkBZqxfotiUZCtcfV7GK88vvFfdatg/NsbqXKow8Dy6ro6KErXJeUwaEfPYSllYx8PTW5+LHAzzGSBE+354D179fdefI7BJmc/FtlweoyeyKrBo/jdg/WlTJPrWR3ppNaDGbhpM+dqCzguGiklRGGafEZFLj/DchLnlmyZnBStK0rZ2zfP6+diC09bF/CaXRd0KTuO5OlMKp163H+4UoYNQp188Elv3Pi2aqqH5GnjgF13tELFyeuua+h56QtWz6TwJV+uFbhaTEj2N+YXz66eSaSNHx0OSzqhSB/CxYRh4RwBzFWDiYZAk1ltWV4B07qGUPZ0HSOA58yZr57wvEU5KpKfyZOopz1Gjq8hBxYDRmAlNtFK8mKLiDpPqhaXDIq2VnAvMTz02hLqxLJ14VQHuPp1m9YS/tzJncPhlAUoSxsYHaSFuBg/i+6mWy1oz5pxwHW9NpedC/CI6PdL6dcsb1WkwLI0spzkEHF/DV7ydox+wRZTpoEi341otbMhU+nsYx7iC85IGmiYVW9pw0ePTQ5mtjXma941rxqIH88qMIMYrgCNCFtE22wugmkwpoFTe2urjbbZojnNXgBBp1Bf1xdIdFGmgoFPXVjqswWBa8AYP+FBgiUvl36yXmr0I2p8lnCrYqtVRo44VFjmwSrFyfiSwHRuw5CO37bObBf
  template:
    metadata:
      creationTimestamp: null
      name: argocd-image-updater-git-creds
      namespace: argocd
    type: Opaque
