apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres-prod

resources:
  - ../../base
  - ../../../../secrets/postgres/prod/postgres-prod-sealed-secret.yaml

patches:
  - path: deployment-patch.yaml
