apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
  labels:
    app: n8n
type: Opaque
data:
  username: bjhu  # n8n in base64
  password: Z2xhc2dvd19wYXNzd29yZA==  # glasgow_password in base64
  db: bjhu  # n8n in base64
