apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
  labels:
    app: n8n
type: Opaque
data:
  N8N_BASIC_AUTH_USER: R2xhc2dvdw==  # Glasgow in base64
  N8N_BASIC_AUTH_PASSWORD: Q29sb2M=  # Coloc in base64
  DB_POSTGRESDB_PASSWORD: bjhuX3Bhc3N3b3Jk  # n8n_password in base64
