apiVersion: batch/v1
kind: Job
metadata:
  name: pgvector-extension-enabler
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: pgvector-enabler
          image: postgres:15
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Waiting for PostgreSQL to be ready..."
              until pg_isready -h postgres-service -p 5432 -U $POSTGRES_USER; do
                sleep 2;
              done;
              echo "PostgreSQL is ready. Enabling pgvector extension..."
              psql -h postgres-service -p 5432 -U $POSTGRES_USER -d $POSTGRES_DB -c "CREATE EXTENSION IF NOT EXISTS vector;"
              echo "pgvector extension enabled successfully."
          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret
