apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome
  namespace: glasgow-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: navidrome
  template:
    metadata:
      labels:
        app: navidrome
    spec:
      containers:
        - name: navidrome
          image: deluan/navidrome:latest
          ports:
            - containerPort: 4533
          volumeMounts:
            - name: data
              mountPath: /data
            - name: music
              mountPath: /music
          env:
          - name: ND_ENABLEINSIGHTSCOLLECTOR
            value: "false"
          - name: ND_LOGLEVEL
            value: info
          - name: ND_SCANSCHEDULE
            value: "1h"
          - name: ND_ADMINUSER
            valueFrom:
              secretKeyRef:
                name: navidrome-credentials-secret
                key: NAVIDROME_ADMIN_USER
          - name: ND_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: navidrome-credentials-secret
                key: NAVIDROME_ADMIN_PASSWORD
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: navidrome-data-pvc
        - name: music
          persistentVolumeClaim:
            claimName: navidrome-music-pvc
