apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yaml
  - ingress.yaml

patchesStrategicMerge:
  - configmap-patch.yaml

replicas:
  - name: fastapi
    count: 2
