apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: fastapi-prod
spec:
  selector:
    app: fastapi
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
