---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: navidrome-credentials-secret
  namespace: glasgow-prod
spec:
  encryptedData:
    NAVIDROME_ADMIN_PASSWORD: AgB9rhPmIqhEl7g+t+KJEhOMSjwZMVyRmwRHet+40qdPwg/CuUR4JDCceDNKKdjVR0sIkBRK3nkT2yq5stl6/xI/Kb8Ngbf0/LkL+HA9hFsQOryZtPk3kUGZX/ZsFlWO26npdEToDO7Zi7/yhLW0P7uiwBhWKzWCXxYBMv4eO0yFMXdorP7+O6OgzObVuBqCc4N6meEMMPhFEFJOVcgL3aD2xrW3hxvztDSk5e6K52VYR5zufGWvQDFnCHctHgdNE57gPCVfIph6VOjVyTVXNnu6YvU5/kQVgjuAP/rFS37g9MCmtJjopyR2eZUqD8X5eDWvB6oogvuOE7ey7oJ9f1FLVP8Q/sGpCm0L+DeWRG8GwZQRWv8c/JgnNA/7TeIBH+4qf1Ee8V6Z3mYkarcQ8jTJgIXeqAyvgK0ei9q7sNRG2ReDEV4tpdOAvXvlmJKgH6kQYP70W4hd9m4P4ECfNOM+vmTxMjJnB2yLJwSyswyFGRUrPjFz9S3//VVtrRHIhSL0/uwISmJDEN+BNYCXjWdexp21ywyrO/R6o3ftcGXvEugoj1ZxCR4jebQ9JUupsATWA/poxuwmT1kezXfpobdphoSOI4Fn4wm4A9HVkgqzbZpmDIScGrldM6FwzwyK/4WRcEppLVZPNPxsHfozoGel668CdxXbbmD3eo3YUHkvYKhYO74bO1eqiPKqoGNIQwAtqWWc7B8iv4U=
    NAVIDROME_ADMIN_USER: AgBSxRvnY7J9U4EYewtDm54KD7yVazYJ6w1DVFCqi5byu9CGKjTngHYsgLF++MH2HR2qR/af1FmimMAUeXImi3zstX+/qaiC8eyrWByhT1Ocya2Bzu8H5vbFUYzPhtjKIy1qQTo9uAhDkmpI6g/be724Q/3cRYfFksvcn5AyEqT4VjJVsypY1OLCDdjnqAFZPDAqdlTLcogE+s5Rv6jbZKZr4Os1H4wGm+ENLHxubil2tdHkJiPatpKPPZYhJrnHR2SGgHLOGJsCBTB4NWPrVK9gzl0d5R64qVCHBwWfmuQCu5uQXh1wsWyTunJRNDd/gMFGP5txUGyHZLH/+eDgdYNF1QXY8uw5Wo1PZRwWwshqZRAV6tqGG2yog8jguwSX26rwAVYFnbSu9gb9kTWvdqUOeMj0NHZfIEPt4K95s/ZB9I/Ob5mh9Xl3K7Eld9JYdJ0vl2TW+yeLiGWT+HIgXD+Bwl96gD/7KyDRcElj3nsKYIu9Pipm4UD1w3ukl9CtpIEW+WJKaWKbzKsHn2oeH9jv4MbPN5KpN0nNJZ6p/a4IdoEmr3sSibNa2EUooLKMtQNJnUN12pIQ/tmdRbV7jn0pkPRKKFsZWNiKyuGgOcSxB5NIWg3e+iLql3ZHKkKY7cSJjCfa4iyUUSIA66FjbIOgGheekLhEyu5Bg1d+i+0TsWji37SIoPNqsl8WrEB+wSBQj70W1Q==
  template:
    metadata:
      creationTimestamp: null
      name: navidrome-credentials-secret
      namespace: glasgow-prod
