---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: glasgow-prod
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAcxEucToTLFrBP5e40QshqPsX6cg8OhJBLQ0nBI5zOAMr9JUtlMvNOD95OEzwaBdobFdtNq1GdkPeAC9Dz+66KFK4WdcExl3I24VL6F2/ClCDCB38BuiuRhVJb8I2bbRc0jLi6YFcxhGQItQsELBtdGeMCCX306tMGtM1bvJeGYX/16jZE5a0CJQbTcxnfynBMdZCJbYxHfwVHI/HSm/jmXf89yIgQFMuRw373Uv+5vz3QT8AK8rCk8tlNDmzrptv30XFoSe0vdFq44bySmLcvkT/i5EFXKupIwCb3iLcUkPKGfEmQl+YFXXlCzkCEQwNqG9TnhDhBbfwH3Q77r06SCgrkw2nDh2fRXvqZURfnWC9J9AV+yxI4eZqZC9oYRdU257PaIN6ZQIxwj4rvic+f8ds4xJnV/zFWCGaETz32JZ+B/m0QVNuZW+cSqkUUiwKrLnb4SmaY71sE4ZyjZR+eERiFHIJ7OgbP8qzOCjpdSHX5ElpnxDkJGchQLjvipCBJpGBUUf4asUwFyIecnDY5xfcn81qiv2/QM8X/PDH9dAEYIX30cQYwjvPWwkCIpFlttlUBO0XLTfm4ovAiQnI580svLax0dWh1CBl+NDuYciJVRnWvrl229fYjuS++lCH0Y6QY+jO9GJCWFOhm2YbFFmxSoKS9WDCNvoyqXHlA4UYiLBXM5qZO/XTRzgfdV5Z3UiUBF8TXPzM=
    POSTGRES_USER: AgAHh8cd1bzsl1OzveLutLlQbaVt2gyUSe9x28wF1938jplByfjhC6x+CO3w0RKS5g/i/E6t7GnajM41NTm14pyEt21fXHdB0/6VsFVlWNfyg1bPpG76d0kxFIK1jo5OFzvuvalJq0w3BeV+eUcE5BhuBnmr1zIb2bH893mpCHAZgySP6Mex/1QAkiBIhxpwJr0pCPcKQtiwADDGBB7xI57YJ175/K98yeaC96tftwU8tJUUPCrJcIpTOVqqkjGFUMc5KcNzrMYJ3y4rLojy5p6uZAJKvw0EC/D4LfueanK6c8k3EHl4EDuJZ2wZsg0SRS4wQiS9I12xV1/9J/AVNyvporzdm7GbQ6i1EwbrK6OdsQMi1NVgihXnG1VMwJGL71E8Fcqv65wqd0SNK2dyTOmKOdyJO08qbZQSKSQ2m9U9xhrxLVDf8OV+/bii21MP0WUUn9Z3LNOZugBrZTsseiLv6eBCRbRoS+xI9GfQ5GGSZJ/DE4ZmM0+s3mOdNIC25FyIDgJqbZEIYCUSrG5c6so05VO6h7y89A+UJhEoo0VObHArcDxoC+qCQi/azwJLpP9TP/D1dhMAqgjimW11wfkT80WqtKZ/We5NC9HQU6d1E7ozYmR8ym4Vb6cyymkJMy45CDUBpwmVJDxXwk13iL+OI6aLk5bAqDbbGqieHLYjtZ25XLxF6zQinbgngPntTlWf5i9JKg==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: glasgow-prod
