apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  labels:
    app: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: your-docker-repo/fastapi:latest
        ports:
        - containerPort: 80
        env:
        - name: ENV_VAR_NAME
          value: "value"  # Replace with your environment variable
        # Add any additional configurations here
      # Add any additional specifications like volumes, etc. if needed