apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glasgow-gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/yourusername/glasgow-gitops.git'
    targetRevision: HEAD
    path: argocd/apps
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true