apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: glasgow-prod

resources:
  - base

  - secrets/prod/postgres-prod-sealed-secret.yaml
  - secrets/prod/minio-prod-sealed-secret.yaml
  - secrets/prod/n8n-postgres-prod-sealed-secret.yaml
  - overlays/prod 

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: kustomize
      environment: prod
