apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Hatchi-Kin/glasgow-gitops.git'  # Back to GitOps repo
    targetRevision: main
    path: components/fastapi/overlays/prod  # Use GitOps manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: fastapi-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true