apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-msv2-api
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: api=hatchikin/msv2-api
    argocd-image-updater.argoproj.io/api.update-strategy: latest
    argocd-image-updater.argoproj.io/api.allow-tags: regexp:^main.*
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: 'https://github.com/Hatchi-Kin/glasgow-gitops.git'
    targetRevision: main
    path: components/fastapi-msv2-api
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: glasgow-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
