apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glasgow-prod-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Hatchi-Kin/glasgow-gitops.git'
    targetRevision: main
    path: components/glasgow-stack
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: glasgow-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true