apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Hatchi-Kin/glasgow-gitops.git'
    targetRevision: HEAD
    path: components/ingress/base
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncWindow:
      schedule: '0 0 * * *'
      duration: 2h