apiVersion: v1
kind: ConfigMap
metadata:
    name: postgres-config
data:
    POSTGRES_DB: ENC[AES256_GCM,data:axNe395mm657h2CE9/CdT/Hw,iv:Igni+RuUpViEA4NI9rBUoxm2WgRNgQLiT6XyPIs0WOE=,tag:2n2Etpi0WonB0KN4GDTvsw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:ODWk65IfFBp7aZV4xiciFA==,iv:zb8DWBkRNOtBi6gs6nqXrxbVM6iyHKw6yhsajB+qiJM=,tag:tW327thFr/KG4IpXN3+Zog==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Z60SF+EABVQtWm4kgAQQ,iv:naVG2R1MXfaCeWPTy/zBJ8SGAtGXOORcMH3z8iaAP1o=,tag:9ZQbxI74R3mkWx+mBZjhLg==,type:str]
sops:
    age:
        - recipient: age1gkehltcs90fvrst9fylsvxcyr4nvf2dasn9hexgnush5zgjlly4qx7wtcm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1UW5oR2pqYmZXelJjVzZu
            SFNvbEd6NkJreW5rMkFrZFZuYVdsNHRwSkE0ClU1dmt2ZFFwVk9yOHlRZHk3ekNN
            NXgwYW40cDE0WG82a3FIaGpWSmFvY1EKLS0tIG9PNGpvUDY3UnBpMFJJNnQwdjY0
            VDFhUmFCWGV2bnRkKzY2LzhjN005OUEKJiuFZpOR1LJMWmUJ2eK1d4FrUbfL3HfU
            pF3+KE9xUQaFGzkxi2xtHnujsLYjsMRyu/gexy0gKw5uo8F2KBwSLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-21T17:24:37Z"
    mac: ENC[AES256_GCM,data:g8A4QBBZ8lnGPSANwAIj5W/LB+4o90S0UdyCkB9rghVKUo9KjK59m5lwRARHSXdeKQpGdgtNQ9VQp4wf/TDiDT14182baXGKYt08e839gTdSologd30O9PSyPIfBTO4Wt1I1I6rhl2Kk0wFQIdamRV1dfHpaug9jnwU8mQlsJME=,iv:3asJTxLMkcOq7LD/um8c0WR4NeqiZPttdVy7oayknCI=,tag:f15223QxDWKtlOXXTQYzIw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
