apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  template:
    spec:
      containers:
      - name: postgres
        env:
          $patch: replace
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: postgres-prod-sealed-secret
                key: db
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-prod-sealed-secret
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-prod-sealed-secret
                key: password
        volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc