apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres-prod

resources:
  - ../../base
  - postgres-prod-sealed-secret.yaml

patchesStrategicMerge:
  - deployment-patch.yaml
