apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - deployment.yaml
  - pvc.yaml
  - postgres-prod-sealed-secret.yaml

patches:
  - path: configmap-patch.yaml
  - path: deployment-patch.yaml