apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: postgres-prod
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:JgBuZ4aiYfbDZiX4dMvOrrI=,iv:D4K1jOH9Y1A8NzRzCkASaJJ3h280igJ1QbCheIyOB0Y=,tag:0tZErPnc3vM6T5lb3V17kw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:rL6PctyHHfnHAiemZrUj,iv:nXL/vvEHi4U8PqbtmwPm1RA8Ok6sfj0nDbkQbEXMqP8=,tag:JgjTFX/awS9pdaTkKDeaKQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:ToNneVHlavJXBPPoeTOo7qU=,iv:K078wYSfHN22PhT9+wHo+fUBqGDrOvmvkYCR9KcfHtY=,tag:gRdZb1ieN6lm3NoWDnf4ZA==,type:str]
sops:
    age:
        - recipient: age1tsp8s27795jhakdpthj8razyx83wdusxqhlhqsqls4cs4gsjtd8s4qauck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2c21QZW5YbThHaTNzaTFk
            ckRreWlyMTZsMHk4cmorV3ZabFNWcm1tZVFRCmZ6TnFnK01mT1d2RlRiUXAyZm80
            Y2R6NkFDQnBpVzUvZTh5RlhFcE5uYmcKLS0tIE9IN3BKcFh6VjdVajNjS01NSE0z
            QWRkOXJhQmVjdTBTYVdsTkdnazVCU00KX9P/WWc15jVkbI6Iub1bKjvV52sjvDUr
            446/b+VpcFORJd5LSyq3n9OoYTuxo3rdElX4dPdaCyLZ13ipYgKgwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-22T00:12:36Z"
    mac: ENC[AES256_GCM,data:UhlTwNFLezBwhx8Codd6dMSznZWEPX7KAbrIaTvps5UaXhsfm9husKRx04Dzbb71aBpdFOr+s+Sljz4jo25zN0mYKsmo41ZchLlMDyDM0Rkx/Ac7IBSfhQB2gmHOUKCIhG+ripNVV9DNgRoRcLUoBBYjqvwlgGVDdLnhbQjfOzo=,iv:QkcDvpS2tF9GscApq97nP3t0l8VjmfsU2n1L2tcXORM=,tag:aEGj/Dn3qFhXRC89PV87Lw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
