apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: postgres-prod
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:ZSb+FKn5068i6fP1gw4U9LY=,iv:riclymby9Y0lqu3ThBewF5aiLE/MJ+jFE71eecZZMD8=,tag:jiYMHNusj3+sTG/zBXWAJQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:HPHCzRi5o6kEpHMQYHkw,iv:vSmREq/VDUK/8HuMnE9V8Ydiw96QhYYv5s3ZmAUUWRY=,tag:kl8H809u1+3ru9PoOXxdpg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:1csLc01DBm/f/0BiVcA6Udk=,iv:krq4jSHJAARFfJzPasN3vRbxd7qNYQ/srDXVa7j7Y2o=,tag:f+oQmfREDQlwCCxWjhJKdw==,type:str]
sops:
    age:
        - recipient: age1ruvxkj57kljhmjr34kvx2cld58f6k68psfx2m6dhcc7wr40dvvfqghlzf5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1aEFpUlJKcWo5QlVwVCt0
            ZElabExOWTgyS3dXZ1NyTFhTbm9ibXBLaEV3Cnk3NmR6aVhYUE5acHQ2QXYxMzhF
            anhSZi9GYS81SzR4c2xGWmJBbE43RlkKLS0tIElhTUVXRFA4K1pxZ3RUQWEvNlBC
            M1pXWDJPVHBHVEE3RHFFNWMyQjRqY3cKVlEy65U7PMBnxThHRU5ZjaHmXodARsyB
            vyjE8r0Qr3vt3gzxYftFwsRK6HG0w45wNDeKt4CyKp4l5YUJCN6vsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-22T00:53:27Z"
    mac: ENC[AES256_GCM,data:iuWjiLptPkPY+ycIKHS8nlULH5n8wRPgGeq+IeDCmzqXTyvbG4sBdL4qiXf46k758qUDgzhN97QY9sxd9g64+8w18T3VPBsh651m1Nn0Zpqkp9Tpcocf1B4jKCpZtuekL/srle/djO+hOCQkeupsI9SWhe9153Zn/95HA70c3QQ=,iv:2rXJz4tz4LuEQlckV2fPMDag3TS0s3M6s+G2fVOc7FU=,tag:rhxyZa+ivK+LFmmMVqHyag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
