apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: glasgow-prod

resources:
  - ../../base
  - ../../secrets/prod/postgres-prod-sealed-secret.yaml
  - ../../secrets/prod/minio-prod-sealed-secret.yaml
  - ../../secrets/prod/n8n-postgres-prod-sealed-secret.yaml

patches:
  - path: fastapi/configmap-patch.yaml
  - path: minio/deployment-patch.yaml
  - path: n8n/deployment-patch.yaml
  - path: postgres/deployment-patch.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: kustomize
      environment: prod
