apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Use 'resources' to point to the base and other files/directories.
# This replaces the deprecated 'bases' field and fixes the warning.
resources:
  # 1. Reference the base directory
  - ../../base

  # 2. Reference the NEW, local path to the secrets
  - secrets/postgres-prod-sealed-secret.yaml
  - secrets/minio-prod-sealed-secret.yaml
  - secrets/n8n-postgres-prod-sealed-secret.yaml
  
  # 3. Reference other overlay-specific resources
  - fastapi/ingress.yaml
  - fastapi/service.yaml
  - n8n/ingress.yaml

# Set the namespace for all resources in this overlay
namespace: glasgow-prod

# Apply patches to modify the base resources
patches:
  # FastAPI Patches
  - path: fastapi/configmap-patch.yaml
    target:
      kind: ConfigMap
      name: fastapi-config
      
  # MinIO Patches
  - path: minio/deployment-patch.yaml
    target:
      kind: Deployment
      name: minio

  # n8n Patches
  - path: n8n/deployment-patch.yaml
    target:
      kind: Deployment
      name: n8n
      
  # Postgres Patches
  - path: postgres/deployment-patch.yaml
    target:
      kind: Deployment
      name: postgres

# Use the 'replicas' transformer to change the replica count for the fastapi deployment
replicas:
  - name: fastapi
    count: 2

# Add common labels to all generated resources
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: kustomize
      environment: prod